name: pleroma prebuilt
on: workflow_dispatch
jobs:
  build:
    name: pleroma [${{matrix.arch}}-${{matrix.os}}]
    runs-on: ${{matrix.runner}}
    strategy:
      fail-fast: true
      matrix:
        arch: [ x86_64 ]
        os: [ ubuntu-20.04, ubuntu-22.04 ]
        version: [ 2.4.4 ]

        include:
          - os: ubuntu-20.04
            runner: ubuntu-20.04
          - os: ubuntu-22.04
            runner: ubuntu-22.04
  
    steps:
      - name: Configure runner
        run: |
          sudo apt update
          sudo apt install git cmake automake autoconf xz-utils
          sudo apt install libmagic-dev libncurses5-dev libssl-dev
          sudo apt install build-essential elixir erlang-dev erlang-nox

      - name: Clone Pleroma
        run: |
          git clone -b v${{matrix.version}} https://git.pleroma.social/pleroma/pleroma /opt/pleroma
          rm -rf /opt/pleroma/.git

      - name: Build Pleroma
        run: |
          cd /opt/pleroma
          mix deps.get
          MIX_ENV=prod time mix compile

      - name: Package Pleroma
        run: |
          PACKAGE_NAME="pleroma-${{matrix.arch}}-${{matrix.os}}"
          tar -cJf ${PACKAGE_NAME}.tar.xz -C /opt pleroma

      - name: Upload Pleroma package
        uses: actions/upload-artifact@v3
        with:
          name: pleroma-${{matrix.arch}}-${{matrix.os}}
          path: pleroma-${{matrix.arch}}-${{matrix.os}}.tar.xz
