name: soapbox prebuilt
on: workflow_dispatch
jobs:
  build:
    name: soapbox
    runs-on: ubuntu-22.04

    steps:
      - name: Clone soapbox
        run: |
          git clone -b v3.0.0-beta.1 https://gitlab.com/soapbox-pub/soapbox.git soapbox

      - name: Build soapbox
        run: |
          cd soapbox
          docker build . -t soapbox
          docker create --name soapbox soapbox
          docker cp soapbox:/usr/share/nginx/html /tmp/soapbox

      - name: Package soapbox
        run: |
          tar -czf soapbox.tar.gz -C /tmp soapbox

      - name: Upload soapbox package
        uses: actions/upload-artifact@v3
        with:
          name: soapbox
          path: soapbox.tar.gz
