name: soapbox prebuilt
on: workflow_dispatch
jobs:
  build:
    name: soapbox
    runs-on: ubuntu-20.04

    steps:
      - name: Configure runner
        run: |
          sudo apt update
          sudo apt install curl git gpg
          sudo apt remove npm nodejs
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.2
          echo ". $HOME/.asdf/asdf.sh" >> ~/.bashrc
          echo ". $HOME/.asdf/completions/asdf.bash" >> ~/.bashrc

      - name: Clone soapbox
        run: |
          git clone -b develop https://gitlab.com/soapbox-pub/soapbox soapbox

      - name: Configure soapbox
        run: |
          cd soapbox
          exec bash
          asdf plugin-add nodejs
          asdf plugin-add yarn
          echo "yarn 1.22.19" >> .tool-versions
          asdf install

      - name: Build soapbox
        env:
          NODE_ENV: production
        run: |
          cd soapbox
          yarn
          yarn build
          mv soapbox/static /tmp/soapbox

      - name: Package soapbox
        run: |
          tar -czf soapbox.tar.gz -C /tmp soapbox

      - name: Upload soapbox package
        uses: actions/upload-artifact@v3
        with:
          name: soapbox
          path: soapbox.tar.gz
